config/routes.rb
Login::Application.routes.draw do
  get "register/index"
  get "register/new"
  post "register/done"
  get "papers/add_mylist"
  get "papers/mylist"
  get "papers/remove_from_mylist"
  get "papers/add_comment"
  post "papers/post_comment"

  resources :papers do

    collection do
      get 'search'
      post 'search'
    end
  end

  get "booklist/hello"

  Login::Application.routes.draw do
  get "register/index"

  resources :papers

  get "booklist/hello"

   resources :sessions
  end

  root :to => 'sessions#new'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :category, :name, :price
end

app/models/mylist.rb
# -*- coding: utf-8 -*-
class Mylist < ActiveRecord::Base
  attr_accessible :account, :title

  validates_uniqueness_of :title, :scope => :account,
    :message => "すでにマイリストに登録されています"
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  attr_accessible :author, :endingPage, :publicationYear, :publicationName, :startingPage, :title, :url

  validates_presence_of :title, :author
  validates_uniqueness_of :title
end

app/models/user.rb
# -*- coding: utf-8 -*-
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :account, :password_digest, :password, :password_confirmation

  validates_presence_of :account, :password,
    :message => 'が記入されていません'
  validates_uniqueness_of :account,
    :message => 'がすでに他のユーザに利用されています'
  validates_length_of :account,
    :maximum => 15,
    :message => 'は15文字以下で記入してください'
  validates_confirmation_of :password,
    :message => 'が確認用パスワードと一致しません'
  validates_length_of :password,
    :minimum => 4,
    :message => 'は4文字以上12文字以下で記入してください'
  validates_length_of :password,
    :maximum => 12,
    :message => 'は4文字以上12文字以下で記入してください'

  REAL_ATTRIBUTE_NAMES = {
    :account => 'ユーザー名',
    :password => 'パスワード',
    :password_confirmation => '確認用パスワード'
  }

  def self.real_attribute_name(key)
    REAL_ATTRIBUTE_NAMES[key.to_sym]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/booklist_controller.rb
class BooklistController < ApplicationController
  def hello
    @booklist = Book.find(:all)
  end
end

app/controllers/papers_controller.rb
# -*- coding: utf-8 -*-
class PapersController < ApplicationController
  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.find(:all, :order => 'created_at desc')
    @query = ""
    @options = "1"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    @paper = Paper.find(params[:id])
    @comments = Mylist.find(:all, :conditions => {:title => @paper.title})

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.json
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, :notice => 'Paper was successfully created.' }
        format.json { render :json => @paper, :status => :created, :location => @paper }
      else
        format.html { render :action => "new" }
        format.json { render :json => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.json
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to @paper, :notice => 'Paper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to papers_url }
      format.json { head :no_content }
    end
  end

  def search
    if params[:options]["id"] == "1"
      @papers = Paper.find(:all, :conditions => ["title like ?", "%"+params[:query]+"%"], :order => 'created_at desc')
    else
      @papers = Paper.find(:all, :conditions => ["author like ?", "%"+params[:query]+"%"], :order => 'created_at desc')
    end

    @query = params[:query]
#    @options = params[:option]["id"]
    render 'index'
  end

  def add_mylist
    @mylist = Mylist.new(params[:data])

    unless @mylist.save
        @head = "登録失敗"
        @msg = "登録が失敗しました。すでにマイリストに登録されています。"
    else
        @head = "登録完了"
        @msg = params[:data][:title] + "はマイリストに登録されました。"
    end
  end

  def mylist
    @titles = Mylist.find(:all, :select => "title", :conditions => { :account => session[:user_name]})
    titles = []
    for t in @titles do
        titles.append(t.title)
    end
    @papers = Paper.find(:all, :conditions => ["title in (?)", titles], :order => "created_at desc")
  end

  def remove_from_mylist
    @mylist = Mylist.find(:first, :conditions => { :account => params[:account], :title => params[:title]})
    @mylist.destroy
    @head = "削除完了"
    @msg = params[:title] + "をマイリストから削除しました"
    render "add_mylist"
  end

  def add_comment
    @message = ""
    @mylist = Mylist.find(:first, :conditions => { :account => params[:account], :title => params[:title]})
  end

  def post_comment
    @mylist = Mylist.find(:first, :conditions => { :account => params[:account], :title => params[:title]})
    @mylist.update_attribute(:comment, params[:comment])
    @message = "登録は正常に行われました"
    render "add_comment"
  end
end

app/controllers/register_controller.rb
# -*- coding: utf-8 -*-
class RegisterController < ApplicationController

  def new
    @user = User.new
  end

  def done
    @user = User.new(params[:user])
    unless @user.save
      render :action => 'new'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    render 'new'
  end

  def create
    user = User.find_by_account(params[:name])
    if user && user.authenticate(params[:pass])
      session[:user_id] = user.id
      session[:user_name] = params[:name]
      redirect_to :controller => 'papers', :action => 'index'
    else
      render 'login_failure'
    end
  end

  def destroy
    session[:user_id] = nil
    render "new"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booklist_helper.rb
module BooklistHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/booklist/hello.html.erb
<h1>ブックリスト</h1>
<p>ようこそ<%= session[:user_name] %>さん</p>
<table border=2>
  <tr>
    <th>商品名</th>
    <th>カテゴリ</th>
    <th>値段</th>
  </tr>
<% @booklist.each do |book| %>
  <tr>
    <td><%= book.name %></td>
    <td><%= book.category %></td>
    <td><%= book.price %></td>
  </tr>
<% end %>
</table>

app/views/booklist/index.html.erb
<h1>ブックリスト</h1>
<p>
販売中の本はこちら
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Papers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- タイトル -->
<div class="title">
  <% if session[:user_id] %>
    <h2><%= link_to "論文データベース", :controller => "papers", :action => "index" %></h2>
  <% else %>
    <h2><%= link_to "論文データベース", :controller => "sessions", :action => "new" %></h2>
  <% end %>
</div>

<div class="nav">
<% if not ["sessions","register"].include?(params[:controller]) %>
  <ul>
    <li><%= link_to "論文リスト", :controller => "papers", :action => "index" %></li>
    <li><%= link_to "マイリスト", :controller => "papers", :action => "mylist" %></li>
    <li><%= link_to "ログアウト", session_path(session[:user_id]), :confirm => 'ログアウトしますか？', :method => :delete %></li>
  </ul>
  <% if session[:user_id] %>
    <p>ようこそ <%= session[:user_name] -%> さん　</p>
  <% end %>
<% end %>
</div>

<!-- コンテントの表示 -->
<div class="content">
  <!-- ヘッダーで隠れる部分 -->
  <br><br><br><br>
  <%= yield %>
</div>

</body>
</html>

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"タイトル(必須)" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :"著者(必須)" %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :URL %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :開始ページ %><br />
    <%= f.number_field :startingPage %>
  </div>
  <div class="field">
    <%= f.label :終了ページ %><br />
    <%= f.number_field :endingPage %>
  </div>
  <div class="field">
    <%= f.label :出版年 %><br />
    <%= f.number_field :publicationYear %>
  </div>
  <div class="field">
    <%= f.label :刊行物名 %><br />
    <%= f.text_field :publicationName %>
  </div>
  <div class="actions">
    <%= f.submit "登録" %>
  </div>
<% end %>

app/views/papers/add_comment.html.erb
<h1>コメントの登録</h1>

<font color="green"><%= @message %></font><br>
<%= @mylist.title %>へのコメント

<%= form_tag ({:action => "post_comment",:account => @mylist.account, :title => @mylist.title}) do %>
<%= text_area_tag("comment", @mylist.comment,:rows=>20, :cols=>100, :style=>"font-size:15px" ) %><br>
<%= submit_tag "登録" %>
<% end %>

<br><br>
<%= link_to '戻る', :action => "mylist" %>

<% if not @mylist.comment.nil? %>
  <div style="background-color: #FFFFDD;">
    <%= Redcarpet.new(@mylist.comment).to_html.html_safe() %>
  </div>
<% end %>

app/views/papers/add_mylist.html.erb
<!-- マイリストへの登録成功、失敗をヘッダに記入 -->
<h1><%= @head %></h1>
<!-- 成功、失敗時のメッセージを表示 -->
<p><%= @msg %></p>
<%= link_to "論文リストへ戻る", :action => "index" %><br>
<%= link_to "マイリストへ移動", :action => "mylist" %>

app/views/papers/edit.html.erb
<h1>論文の登録内容の編集</h1>

<%= render 'form' %>

<%= link_to '詳細を見る', @paper %> |
<%= link_to '戻る', :back %>

app/views/papers/index.html.erb
<!-- クエリが入力されていたら検索結果へ、なければ論文リストへ -->
<h1>
<% if @query == "" %>
論文リスト
<% else %>
検索結果
<% end %>
</h1>

<%= link_to '新しい論文を登録', new_paper_path %>
<br>

<!-- 検索フォーム -->
<table>
<%= form_tag :action=>"search" do %>
    <td><%= select_tag 'options[id]', options_for_select([["タイトルで検索", "1"], ["著者名で検索", "2"]]), :style => "font-size:21px" %></td>
    <td><%= text_field_tag :query, @query, :style => "height:21px;font-size:15px", :size => 40 %></td>
    <td><%= image_submit_tag("/assets/search.png") %></td>
<% end %>
</table>

<!-- 論文が1件も登録されていなければtableを表示しない -->
<% if @papers.length == 0 %>
  <p>該当なし</p>
<% else %>

  <p>全<%= @papers.length %>件</p>

  <table class="list">
    <tr>
      <th>タイトル</th>
      <th>著者</th>
      <th>投稿日時</th>
      <th></th>
      <th></th>
    </tr>

    <% @papers.each do |paper| %>
      <tr>
	<td><%= link_to paper.title, paper %></td>
	<td><%= paper.author %></td>
	<td><%= paper.created_at %></td>
	<td width=40px><%= link_to '編集', edit_paper_path(paper) %></td>
	<td width=40px><%= link_to '削除', paper, :method => :delete, :data => { :confirm => '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/papers/mylist.html.erb
<h1>マイリスト</h1>

<!-- マイリストの登録件数が0ならtableを表示しない -->
<% if @papers.length == 0 %>
  <p>マイリストに論文が登録されていません</p>
  <%= @titles %>
<% else %>

  <p>全<%= @papers.length %>件</p>

  <table class="list">
    <tr>
      <th>タイトル</th>
      <th>著者</th>
      <th></th>
      <th></th>
    </tr>

    <% @papers.each do |paper| %>
      <tr>
	<td><%= link_to paper.title, paper %></td>
	<td><%= paper.author %></td>
	<td width = 80px><%= link_to 'コメントを登録', {:action => "add_comment", :account => session[:user_name], :title => paper.title} %></td>
	<td width = 80px><%= link_to 'マイリストから削除', {:action => "remove_from_mylist", :account => session[:user_name], :title => paper.title}, { :confirm => "本当に削除しますか?" } %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/papers/new.html.erb
<h1>論文の新規登録</h1>

<%= render 'form' %>

<%= link_to '戻る', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<table>
<tr>
  <td>タイトル:</td>
  <td><%= @paper.title %></td>
</tr>

<tr>
  <td>著者:</td>
  <td><%= @paper.author %></td>
</tr>

<tr>
  <td>URl:</td>
  <td><%= @paper.url %></td>
</tr>

<tr>
  <td>開始ページ:</td>
  <td><%= @paper.startingPage %></td>
</tr>

<tr>
  <td>終了ページ:</td>
  <td><%= @paper.endingPage %></td>
</tr>

<tr>
  <td>出版年:</td>
  <td><%= @paper.publicationYear %></td>
</tr>

<tr>
  <td>刊行物名:</td>
  <td><%= @paper.publicationName %></td>
</tr>

</table>

<br>
<%= link_to 'この論文を読む', @paper.url, :target => "_blank" %>
<br>

<%= link_to_function("bibtexを表示", "show_bibtex(0);") %>
<br>

<div id="bibtex", style="display:none;background-color:white;">
<%= "@inproceedings{" + (("a".."z").to_a + ("A".."Z").to_a + (0..9).to_a).shuffle[0..5].join + "," %></br>
<%= "author = {" + @paper.author + "}," %></br>
<%= "title = {" + @paper.title + "}," %></br>
<%= "booktitle = {" + @paper.publicationName + "}," %></br>
<%= "year = {" + @paper.publicationYear.to_s + "}," %></br>
}</br>
</div>

<%= link_to 'マイリストに追加', :controller => "papers", :action => "add_mylist", :data => {:account => session[:user_name], :title => @paper.title} %>
<br>

<%= link_to '編集', edit_paper_path(@paper) %> |
<%= link_to '戻る', :back %>

<div id="comments">
  <% @comments.each do |comment| %>
    <% if not comment.comment.nil? %>
      <div style="background-color: #FFFFDD">
        <%= Redcarpet.new(comment.comment).to_html.html_safe() %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/register/done.html.erb
<h1>登録完了</h1>
<p><%= @user[:account] -%>さんのアカウントが新規作成されました</P>
<%= link_to "ログイン画面へ", :controller => "sessions", :action => "new" %>

app/views/register/new.html.erb
<h1>アカウントの新規登録</h1>

<!-- エラーメッセージ -->
<div class="errors">
<% keys = [:account, :password, :password_confirmation] %>
<% @user.errors.each do |attr,msg| %>
  <% if keys.include?(attr) && msg != "doesn't match confirmation" %>
    <%= User.real_attribute_name(attr) %><%= msg %><br>
  <% end %>
<% end %>
</div>

<!-- 入力フォーム -->
<table>
<%= form_for :user, :url => {:action => 'done'} do |f| %>
  <tr>
    <td>ユーザー名</td>
    <td><%= f.text_field :account %></td>
    <td>(15文字以下)</td>
  </tr>
  <tr>
    <td>パスワード</td>
    <td><%= f.password_field :password %></td>
    <td>(4文字以上12文字以下)
  </tr>
  <tr>
    <td/>
    <td><%= f.password_field :password_confirmation %></td>
    <td>(確認用)</td>
  </tr>
</table>
  <div>
    <%= submit_tag '登録' %>
  </div>
<% end %>

<%= link_to 'ログイン画面に戻る', :controller => "sessions", :action => "new" %>